# Site settings
title: Codequeen1110's Blog
header-img: img/home-bg.png
email: purnima0912@hotmail.com
copyright_name: codequeen1110
description: > # this means to ignore newlines until "baseurl:"
  Blogging my journey as codequeen1110
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: codequeen1110
github_username:  codequeen1110
learn_profile: codequeen1110
email_username: purnima0912@hotmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
